source 'https://cdn.cocoapods.org'

platform :ios, '14.1'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'Shared', :path => '../Shared'

end
